name: ecommerce_application_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
# Dependencias de firebase
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

