// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtfAyEltn4MHziw1ye8mrC60jZua3Yjc',
    appId: '1:1060136144187:web:4388ef5847fc6f39c17b1e',
    messagingSenderId: '1060136144187',
    projectId: 'flutter-test-f5ce5',
    authDomain: 'flutter-test-f5ce5.firebaseapp.com',
    storageBucket: 'flutter-test-f5ce5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn42V3-NosPPAuS087q2zKbIYwRC76oRc',
    appId: '1:1060136144187:android:afa8695c119bf91ac17b1e',
    messagingSenderId: '1060136144187',
    projectId: 'flutter-test-f5ce5',
    storageBucket: 'flutter-test-f5ce5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi6s2mQE9O3FsxR4pKi4KgewWsynNQdFk',
    appId: '1:1060136144187:ios:711f7f5e57890458c17b1e',
    messagingSenderId: '1060136144187',
    projectId: 'flutter-test-f5ce5',
    storageBucket: 'flutter-test-f5ce5.appspot.com',
    iosBundleId: 'com.example.ecommerceApplication01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi6s2mQE9O3FsxR4pKi4KgewWsynNQdFk',
    appId: '1:1060136144187:ios:711f7f5e57890458c17b1e',
    messagingSenderId: '1060136144187',
    projectId: 'flutter-test-f5ce5',
    storageBucket: 'flutter-test-f5ce5.appspot.com',
    iosBundleId: 'com.example.ecommerceApplication01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMtfAyEltn4MHziw1ye8mrC60jZua3Yjc',
    appId: '1:1060136144187:web:0f67de5f79525b35c17b1e',
    messagingSenderId: '1060136144187',
    projectId: 'flutter-test-f5ce5',
    authDomain: 'flutter-test-f5ce5.firebaseapp.com',
    storageBucket: 'flutter-test-f5ce5.appspot.com',
  );

}